Repository cisco-ie/ez-dash, pull requests merged in 2018-04, with the labels that each got.

#9 File*cough*Metricbeat
  build_images.sh
  docker-compose.yml
  logstash/.gitkeep
  metricbeat/Dockerfile
  metricbeat/metricbeat.yml
  start.sh
Labels: feature

#10 Add preconfigured Grafana datasources
  docker-compose.yml
  grafana/.gitkeep
  grafana/datasources.yml
Labels: enhancement

#13 Update for InfluxDB
  docker-compose.yml
  grafana/datasources.yml
  python/Pipfile
  python/main.py
Labels: enhancement

#14 Grafana ES Dashboard
  .gitignore
  docker-compose.yml
  grafana/dashboards.yml
  grafana/dashboards/Cluster Health.json
  grafana/datasources.yml
Labels: feature

#17 Graphs
  docker-compose.yml
  grafana/dashboards.yml
  grafana/dashboards/App Stats.json
  grafana/dashboards/Cluster Health.json
  python/main.py
Labels: feature

#18 Simplify Prometheus Config
  docker-compose.yml
  grafana/dashboards/App Stats.json
  prometheus/prometheus.yml
  prometheus/rules.d/test.rule
Labels: enhancement

#19 Use configs and change InfluxDB db to ezdash
  docker-compose.yml
  grafana/datasources.yml
  python/main.py
Labels: enhancement

#20 Add Windows batch scripts
  build_images.bat
  setup.bat
  start.bat
  stop.bat
Labels: enhancement

#21 Python App Stat Gen
  grafana/dashboards/App Stats.json
  python/Pipfile
  python/main.py
Labels: enhancement

#22 Add Flask App
  docker-compose.yml
  grafana/dashboards/App Stats.json
  python/Pipfile
  python/main.py
Labels: enhancement

#23 Fix InfluxDB connection failure error
  python/main.py
Labels: bug
